"""empty message

Revision ID: 2e299d84fbf0
Revises: 66ee11b07f4b
Create Date: 2022-01-15 10:25:24.143411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e299d84fbf0'
down_revision = '66ee11b07f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_name_key', 'business', type_='unique')
    op.drop_column('business', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('business_name_key', 'business', ['name'])
    # ### end Alembic commands ###
