"""empty message

Revision ID: 390bef55d5a1
Revises: 641c62884df8
Create Date: 2021-12-18 19:28:52.888130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390bef55d5a1'
down_revision = '641c62884df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
