"""empty message

Revision ID: 4205ef6cf558
Revises: 9bc746022831
Create Date: 2022-01-10 11:55:33.366633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4205ef6cf558'
down_revision = '9bc746022831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'duration')
    # ### end Alembic commands ###
