"""empty message
Revision ID: 641c62884df8
Revises: b46bf387775e
Create Date: 2021-12-18 18:35:23.878925
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641c62884df8'
down_revision = 'b46bf387775e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###