"""empty message

Revision ID: 66ee11b07f4b
Revises: 113d2299ea69
Create Date: 2022-01-15 10:00:01.321980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ee11b07f4b'
down_revision = '113d2299ea69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('weekdays', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'weekdays')
    # ### end Alembic commands ###
