"""empty message

Revision ID: 80bca186b876
Revises: b9f0f5a811bc
Create Date: 2022-01-24 19:04:45.241152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bca186b876'
down_revision = 'b9f0f5a811bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
