"""empty message

Revision ID: 83e16837539b
Revises: f9f4d3bcb769
Create Date: 2022-01-24 18:36:29.113740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e16837539b'
down_revision = 'f9f4d3bcb769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'book', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_column('book', 'email')
    # ### end Alembic commands ###
