"""empty message

Revision ID: 9bc746022831
Revises: e50d42d435f8
Create Date: 2022-01-08 12:17:33.295565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc746022831'
down_revision = 'e50d42d435f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_email_key', 'book', type_='unique')
    op.create_foreign_key(None, 'book', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_column('book', 'product')
    op.drop_column('book', 'email')
    op.add_column('dispo', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dispo', 'product', ['product_id'], ['id'])
    op.drop_column('dispo', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispo', sa.Column('product', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dispo', type_='foreignkey')
    op.drop_column('dispo', 'product_id')
    op.add_column('book', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('book', sa.Column('product', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_unique_constraint('book_email_key', 'book', ['email'])
    op.drop_column('book', 'user_id')
    op.drop_column('book', 'product_id')
    # ### end Alembic commands ###
