"""empty message

Revision ID: a436533024b4
Revises: 36c342daa884
Create Date: 2022-01-15 12:17:38.821421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a436533024b4'
down_revision = '36c342daa884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('business', 'phone',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('business', 'schedule',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('business', 'weekdays',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'weekdays',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('business', 'schedule',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('business', 'phone',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('business', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
