"""empty message

Revision ID: b9f0f5a811bc
Revises: 83e16837539b
Create Date: 2022-01-24 18:38:46.448051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f0f5a811bc'
down_revision = '83e16837539b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_email_key', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('book_email_key', 'book', ['email'])
    # ### end Alembic commands ###
