"""empty message

Revision ID: bae49a8827ab
Revises: 8db5226ec40a
Create Date: 2021-12-21 19:05:50.100170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae49a8827ab'
down_revision = '8db5226ec40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'product', ['product_id'], ['id'])
    op.drop_column('book', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('product', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'product_id')
    # ### end Alembic commands ###
