"""empty message

Revision ID: be73926ec17d
Revises: 4205ef6cf558
Create Date: 2022-01-10 12:05:45.976603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be73926ec17d'
down_revision = '4205ef6cf558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('product', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
