"""empty message

Revision ID: ef5d29aff2a0
Revises: 2e299d84fbf0
Create Date: 2022-01-15 11:21:53.762996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5d29aff2a0'
down_revision = '2e299d84fbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_active')
    # ### end Alembic commands ###
