"""empty message

Revision ID: fe91e0e2f080
Revises: 2742b42c4e1e
Create Date: 2022-01-23 11:03:55.682737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe91e0e2f080'
down_revision = '2742b42c4e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('public_id', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'service', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='unique')
    op.drop_column('service', 'public_id')
    # ### end Alembic commands ###
